// Opt-in integration check: uploads temporary drafts to Qiniu, deletes them, never generates images.
// Synthetic fixtures stay in memory; HEIC sample is fetched from libheif's official repository.
const {chromium}=require('playwright');const sharp=require('sharp');const {execFileSync}=require('child_process');const assert=require('assert/strict');
(async()=>{const base=process.env.IMAGE_TOOLS_TEST_URL || 'http://127.0.0.1:8000';const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const c=await b.newContext({viewport:{width:390,height:844}});let taskId;try{const p=await c.newPage();let authorized=[];p.on('request',r=>{if(r.url().includes('/assets/')&&r.postData()?.includes('authorize'))authorized.push(JSON.parse(r.postData()));});p.on('response',async r=>{if(new URL(r.url()).pathname==='/api/image-tasks/'&&r.request().method()==='POST'&&r.status()===201)taskId=(await r.json()).task.id;});await p.goto(base+'/tools/cartoon',{waitUntil:'networkidle'});
const img=()=>sharp({create:{width:96,height:64,channels:4,background:{r:255,g:80,b:0,alpha:.5}}});
const bmp=Buffer.alloc(54+96*64*3);bmp.write('BM');bmp.writeUInt32LE(bmp.length,2);bmp.writeUInt32LE(54,10);bmp.writeUInt32LE(40,14);bmp.writeInt32LE(96,18);bmp.writeInt32LE(64,22);bmp.writeUInt16LE(1,26);bmp.writeUInt16LE(24,28);bmp.fill(180,54);
const fixtures=[['unknown.dat','application/octet-stream',await img().jpeg().toBuffer()],['photo.avif','image/avif',await img().avif().toBuffer()],['photo.bmp','image/bmp',bmp],['photo.gif','image/gif',await img().gif().toBuffer()],['photo.tiff','image/tiff',await img().withMetadata({orientation:6}).tiff({compression:'lzw'}).toBuffer()],['photo.heic','image/heic',execFileSync('curl',['-fsSL','https://raw.githubusercontent.com/strukturag/libheif/master/examples/example.heic'],{maxBuffer:20*1024*1024})]];
for(const [name,mimeType,buffer]of fixtures){const complete=p.waitForResponse(r=>r.url().includes('/assets/')&&r.request().postData()?.includes('complete'),{timeout:120000});await p.locator('input[type=file]').setInputFiles({name,mimeType,buffer});const r=await complete;assert.equal(r.status(),201,await r.text());await p.waitForTimeout(500);console.log(JSON.stringify({name,inputBytes:buffer.length,uploadMime:authorized.at(-1).mime,uploadBytes:authorized.at(-1).size}));}
const token=(await c.cookies()).find(x=>x.name==='token').value;const result=await(await c.request.get(base+'/api/image-tasks/'+taskId+'/',{headers:{Authorization:token}})).json();assert.equal(result.task.inputs.length,6);const tiff=result.task.inputs[4];assert.equal(tiff.width,64);assert.equal(tiff.height,96);assert.equal(result.task.status,'draft');for(const index of [1,4]){const image=await c.request.get(base+'/api'+result.task.inputs[index].url);assert.equal(image.status(),200);const {data,info}=await sharp(await image.body()).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert(info.channels===4);assert(data[3]>110&&data[3]<145,'Transparency must survive conversion');}console.log('PASS six formats, TIFF orientation, guest upload and draft state.');}finally{if(taskId){const token=(await c.cookies()).find(x=>x.name==='token')?.value;await c.request.delete(base+'/api/image-tasks/'+taskId+'/',{headers:{Authorization:token}});}await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
